apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-affinity-node2
spec:
  containers:
  - name: nginx-pod-affinity-node2
    image: nginx
  affinity:
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-type
            operator: In
            values: ["nginx", "linux"]
               


