apiVersion: v1
kind: Pod
metadata: 
  name: tain-toler-app
spec: 
  tolerations:
  - key: app
    operator: Exists
    effect: NoSchedule
  - key: env
    operator: Equal
    value: prod
    effect: NoExecute
  containers: 
  - name: webim
    image: nginx
